[build]
  command = "pnpm build:deploy"
  publish = "dist/site"

[build.environment]
  NODE_VERSION = "22.17.1"

[[redirects]]
  from = "/"
  to = "/pipes/"
  status = 302
  force = true

[[headers]]
  for = "/cssflower/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/cssgears/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/cssgears/scenes/*.gz"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/cssmenger/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
